version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: company_db
      POSTGRES_USER: company_user
      POSTGRES_PASSWORD: company_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: ./base
    command: gunicorn --bind 0.0.0.0:8000 base.wsgi:application
    volumes:
      - .:/base:/base
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      REACT_APP_API_URL: http://localhost:8000/api