# Generated by Django 5.2.1 on 2025-05-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=12, unique=True)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cost_of_sales', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gross_profit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('commercial_expenses', models.DecimalField(decimal_places=2, max_digits=15)),
                ('administrative_expenses', models.DecimalField(decimal_places=2, max_digits=15)),
                ('pre_tax_profit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=15)),
                ('net_profit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_assets', models.DecimalField(decimal_places=2, max_digits=15)),
                ('non_current_assets', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_assets', models.DecimalField(decimal_places=2, max_digits=15)),
                ('equity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('long_term_liabilities', models.DecimalField(decimal_places=2, max_digits=15)),
                ('short_term_liabilities', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_liabilities', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
    ]
